server.port=4000

spring.datasource.url=jdbc:postgresql://localhost:5433/employee
spring.datasource.username=wcrs
spring.datasource.password=wcrs
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.hibernate.format_sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=POSTGRESQL


