server:
  port: 4000

spring:
  datasource:
    url: jdbc:postgresql://wcrs-db:5432/employee
    username: wcrs
    password: wcrs
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    show-sql: true
    database: POSTGRESQL

  boot:
    admin:
      client:
        url: http://admin:9090
        enabled: true
        auto-registration: true
        instance:
          name: ${spring.application.name:JSS}

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
      
